# Generated by Django 5.1 on 2024-09-01 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Library_management", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="titel",
            new_name="title",
        ),
    ]
