# Generated by Django 5.1 on 2024-09-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Library_management", "0002_rename_titel_book_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="user",
        ),
        migrations.RemoveField(
            model_name="book",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="book",
            name="publicationdate",
            field=models.DateField(),
        ),
    ]
